export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_DETAILS_REQUEST = "FETCH_DETAILS_REQUEST";
export const FETCH_DETAILS_FAILURE = "FETCH_DETAILS_FAILURE";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
